<?php
/**
 * @file
 * menu_link.d5a2d69870717510ae152eae169a963cba521868.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => '<front>',
  'link_title' => 'Home',
  'menu_name' => 'main-menu',
  'weight' => '-48',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
    'alter' => TRUE,
  ),
  'router_path' => '',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.main_menu' => 'menu.main_menu',
);

$optional = array();

$modules = array();
