<?php
/**
 * @file
 * menu_link.c630a554b4d31f68e37da0fb6da68bd8ed9337e2.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/reports/page-title',
  'link_title' => 'Page Title List',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'List all nodes with their Page Titles',
    ),
  ),
  'router_path' => 'admin/reports/page-title',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.navigation' => 'menu.navigation',
);

$optional = array();

$modules = array();
