<?php
/**
 * @file
 * menu_link.244a8183b658cf9a996c1f79b5ba42c346105ab6.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/content/ckeditor',
  'link_title' => 'CKEditor',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure the rich text editor.',
    ),
  ),
  'router_path' => 'admin/config/content/ckeditor',
  'parent_identifier' => '0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$dependencies = array(
  'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff' => 'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$optional = array();

$modules = array();
