<?php
/**
 * @file
 * menu_link.68657e46cd0a471132801d41712f948fe886cbca.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/pages',
  'link_title' => 'Pages',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Add, edit and remove overridden system pages and user defined pages from the system.',
    ),
  ),
  'router_path' => 'admin/structure/pages',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
