<?php
/**
 * @file
 * menu_link.6df6e207ab1d96616bd4875ef4b6591b8cbeee70.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/media/picture',
  'link_title' => 'Picture mappings',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage picture mappings.',
    ),
  ),
  'router_path' => 'admin/config/media/picture',
  'parent_identifier' => 'a0ac7769dd155924a164eb528a16bc61c42033cf',
);

$dependencies = array(
  'menu_link.a0ac7769dd155924a164eb528a16bc61c42033cf' => 'menu_link.a0ac7769dd155924a164eb528a16bc61c42033cf',
);

$optional = array();

$modules = array();
