<?php
/**
 * @file
 * menu_link.fa244a00852203f1cc57391ad418df41a9f52636.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/search/xmlsitemap',
  'link_title' => 'XML sitemap',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure your site\'s XML sitemaps to help search engines find and index pages on your site.',
    ),
  ),
  'router_path' => 'admin/config/search/xmlsitemap',
  'parent_identifier' => 'ef0082661602f85e5c700d4bd929cfa3db5d543f',
);

$dependencies = array(
  'menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f' => 'menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f',
);

$optional = array();

$modules = array();
