<?php
/**
 * @file
 * menu_link.383af6e1b54a549a9f0af3662b9f9b5aff5254c0.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/system/globalredirect',
  'link_title' => 'Global Redirect',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Chose which features you would like enabled for Global Redirect',
    ),
  ),
  'router_path' => 'admin/config/system/globalredirect',
  'parent_identifier' => '4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$dependencies = array(
  'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6' => 'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$optional = array();

$modules = array();
