<?php
/**
 * @file
 * menu_link.efa6a266d40d8df3c4369814ea5473a79f72480e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'user/login',
  'link_title' => 'Login',
  'menu_name' => 'menu-footer-links',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
  ),
  'router_path' => 'user/login',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_footer_links' => 'menu.menu_footer_links',
);

$optional = array();

$modules = array();
