<?php
/**
 * @file
 * menu_link.9211a8d5179f49a72c8bf7f2cd7d650d88e3757e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/add/producto',
  'link_title' => 'Producto',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'node/add/producto',
  'parent_identifier' => '7fa6a77950f9dfec910f197544505e3fb2f92723',
);

$dependencies = array(
  'menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723' => 'menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723',
);

$optional = array();

$modules = array();
