<?php
/**
 * @file
 * menu_link.56dcb82492629d20d2f7ae4034149e29ed7c2cf8.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/content/ckeditor_link',
  'link_title' => 'CKEditor Link',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure CKEditor Link.',
    ),
  ),
  'router_path' => 'admin/config/content/ckeditor_link',
  'parent_identifier' => '0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$dependencies = array(
  'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff' => 'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$optional = array();

$modules = array();
