<?php
/**
 * @file
 * menu_link.b55d8ebd9e8c611470dfe31908fe23e9ba96e9aa.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/regional/i18n_translation',
  'link_title' => 'Translation sets',
  'menu_name' => 'management',
  'weight' => '10',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Translation sets overview.',
    ),
  ),
  'router_path' => 'admin/config/regional/i18n_translation',
  'parent_identifier' => '29a0beace8faac4356003f60d9b4c5feb87d38f3',
);

$dependencies = array(
  'menu_link.29a0beace8faac4356003f60d9b4c5feb87d38f3' => 'menu_link.29a0beace8faac4356003f60d9b4c5feb87d38f3',
);

$optional = array();

$modules = array();
