<?php
/**
 * @file
 * menu_link.a03994eaa822deb3c5550fc0e4e578d95fc087f9.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/panels',
  'link_title' => 'Panels',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Get a bird\'s eye view of items related to Panels.',
    ),
  ),
  'router_path' => 'admin/structure/panels',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
