<?php
/**
 * @file
 * menu_link.fcb46bf1792a7a1898eabe8b9fa218d050f57c69.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/user-interface/modulefilter',
  'link_title' => 'Module filter',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure how the modules page looks and acts.',
    ),
  ),
  'router_path' => 'admin/config/user-interface/modulefilter',
  'parent_identifier' => '5440005a9acc41ae6ea0335a022797c71396bfe5',
);

$dependencies = array(
  'menu_link.5440005a9acc41ae6ea0335a022797c71396bfe5' => 'menu_link.5440005a9acc41ae6ea0335a022797c71396bfe5',
);

$optional = array();

$modules = array();
