<?php
/**
 * @file
 * menu_link.b8f7ed8a0d1fb07a7a058f25688a5dd2c97f7d96.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/development/generate/redirects',
  'link_title' => 'Generate redirects',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Generate a given number of redirects. Optionally delete current redirects.',
    ),
  ),
  'router_path' => 'admin/config/development/generate/redirects',
  'parent_identifier' => '85036b299694ce25b3be992e83036f020ee9651d',
);

$dependencies = array(
  'menu_link.85036b299694ce25b3be992e83036f020ee9651d' => 'menu_link.85036b299694ce25b3be992e83036f020ee9651d',
);

$optional = array();

$modules = array();
