<?php
/**
 * @file
 * menu_link.415a48f548a8dffe9df687a1b7fbcb12eb982cb2.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/search/metatags',
  'link_title' => 'Metatag',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure Metatag defaults.',
    ),
  ),
  'router_path' => 'admin/config/search/metatags',
  'parent_identifier' => 'ef0082661602f85e5c700d4bd929cfa3db5d543f',
);

$dependencies = array(
  'menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f' => 'menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f',
);

$optional = array();

$modules = array();
