<?php
/**
 * @file
 * menu_link.9930e6881aeaff13280d08a6932ddd021babc39f.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/content/background-images',
  'link_title' => 'Background Images',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage your site\'s background images',
    ),
  ),
  'router_path' => 'admin/content',
  'parent_identifier' => 'c43a58aeada3d70ae9f892c266f3a54854394950',
);

$dependencies = array(
  'menu_link.c43a58aeada3d70ae9f892c266f3a54854394950' => 'menu_link.c43a58aeada3d70ae9f892c266f3a54854394950',
);

$optional = array();

$modules = array();
