<?php
/**
 * @file
 * menu_link.24cf7bb3730bd6c2aa3f659c9180802827f03687.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/2',
  'link_title' => 'Contacto y localización',
  'menu_name' => 'main-menu',
  'weight' => '-45',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'node/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.main_menu' => 'menu.main_menu',
);

$optional = array();

$modules = array();
