<?php
/**
 * @file
 * menu_link.1a4bc33cc3b059700fa70bcb5d5ba028ef5a4e05.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/content/background-image',
  'link_title' => 'Background Image',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Settings for how to apply the background image to the page',
    ),
  ),
  'router_path' => 'admin/config/content/background-image',
  'parent_identifier' => '0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$dependencies = array(
  'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff' => 'menu_link.0abfc766397248b728a2eb15b845fda3aa5aefff',
);

$optional = array();

$modules = array();
