<?php
/**
 * @file
 * menu_link.af8a106f7a38d2c6d1954de2cf038986f7fe745e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/flags',
  'link_title' => 'Flags',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure flags for marking content with arbitrary information (such as <em>offensive</em> or <em>bookmarked</em>).',
    ),
  ),
  'router_path' => 'admin/structure/flags',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
