<?php
/**
 * @file
 * menu_link.cd67fceb4707736b41a8b4e356996fa383d4388a.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/search/redirect',
  'link_title' => 'URL redirects',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Redirect users from one URL to another.',
    ),
  ),
  'router_path' => 'admin/config/search/redirect',
  'parent_identifier' => 'ef0082661602f85e5c700d4bd929cfa3db5d543f',
);

$dependencies = array(
  'menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f' => 'menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f',
);

$optional = array();

$modules = array();
