<?php
/**
 * @file
 * menu_link.6aa4872906c2244834c9f075185f5bc87da55e82.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/content/file',
  'link_title' => 'Files',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage files used on your site.',
    ),
  ),
  'router_path' => 'admin/content/file',
  'parent_identifier' => 'c43a58aeada3d70ae9f892c266f3a54854394950',
);

$dependencies = array(
  'menu_link.c43a58aeada3d70ae9f892c266f3a54854394950' => 'menu_link.c43a58aeada3d70ae9f892c266f3a54854394950',
);

$optional = array();

$modules = array();
