<?php
/**
 * @file
 * menu_link.0d4b6b9668e31a9a5d3d20387f36880e1ef94477.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'devel/php',
  'link_title' => 'Execute PHP Code',
  'menu_name' => 'devel',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Execute some PHP code',
    ),
  ),
  'router_path' => 'devel/php',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.devel' => 'menu.devel',
);

$optional = array();

$modules = array();
