<?php
/**
 * @file
 * menu_link.5a5f2e3a320f18c73094abece1f16909ce9e737a.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/media/breakpoints',
  'link_title' => 'Breakpoints',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage breakpoints',
    ),
  ),
  'router_path' => 'admin/config/media/breakpoints',
  'parent_identifier' => 'a0ac7769dd155924a164eb528a16bc61c42033cf',
);

$dependencies = array(
  'menu_link.a0ac7769dd155924a164eb528a16bc61c42033cf' => 'menu_link.a0ac7769dd155924a164eb528a16bc61c42033cf',
);

$optional = array();

$modules = array();
