<?php
/**
 * @file
 * menu_link.f9170c0f0fd124f2cea440fbbd909aa0ccc4b428.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/add/front-page',
  'link_title' => 'Front Page',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'node/add/front-page',
  'parent_identifier' => '7fa6a77950f9dfec910f197544505e3fb2f92723',
);

$dependencies = array(
  'menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723' => 'menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723',
);

$optional = array();

$modules = array();
