<?php
/**
 * @file
 * menu_link.1ce6b19fbb614791d3edee4f428625c5f9c5f953.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'file/add',
  'link_title' => 'Add file',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'file/add',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.navigation' => 'menu.navigation',
);

$optional = array();

$modules = array();
