<?php
/**
 * @file
 * menu_link.be77ebd8c10f1dcb3d23df18548a1dc616955d97.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/administration/adminimal_menu',
  'link_title' => 'Adminimal menu',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Adjust adminimal menu settings.',
    ),
  ),
  'router_path' => 'admin/config/administration/adminimal_menu',
  'parent_identifier' => 'ada990f9339b55d703abdf1d3baae0268477fa51',
);

$dependencies = array(
  'menu_link.ada990f9339b55d703abdf1d3baae0268477fa51' => 'menu_link.ada990f9339b55d703abdf1d3baae0268477fa51',
);

$optional = array();

$modules = array();
