<?php
/**
 * @file
 * menu_link.1937bee411ccc32e4661d61e109f3a0634ae094e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/ds',
  'link_title' => 'Display Suite',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage layouts for entities and configure fields, view modes etc.',
    ),
  ),
  'router_path' => 'admin/structure/ds',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
