<?php
/**
 * @file
 * menu_link.059849b8d0b373ededf090d736e5645a312658fa.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/media/file-settings',
  'link_title' => 'File settings',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure allowed file extensions, default alt and title sources, and the file upload wizard.',
    ),
  ),
  'router_path' => 'admin/config/media/file-settings',
  'parent_identifier' => 'a0ac7769dd155924a164eb528a16bc61c42033cf',
);

$dependencies = array(
  'menu_link.a0ac7769dd155924a164eb528a16bc61c42033cf' => 'menu_link.a0ac7769dd155924a164eb528a16bc61c42033cf',
);

$optional = array();

$modules = array();
