<?php
/**
 * @file
 * menu_link.5d6103d658020c0a9d77f0a4af092f137766ec6a.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/regional/entity_translation',
  'link_title' => 'Entity translation',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure which entities can be translated and enable or disable language fallback.',
    ),
  ),
  'router_path' => 'admin/config/regional/entity_translation',
  'parent_identifier' => '29a0beace8faac4356003f60d9b4c5feb87d38f3',
);

$dependencies = array(
  'menu_link.29a0beace8faac4356003f60d9b4c5feb87d38f3' => 'menu_link.29a0beace8faac4356003f60d9b4c5feb87d38f3',
);

$optional = array();

$modules = array();
