<?php
/**
 * @file
 * menu_link.81bd549dd960b8a0c44eeea32315f3a7cbe2e71f.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/media/browser',
  'link_title' => 'Media browser settings',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure the behavior and display of the media browser.',
    ),
  ),
  'router_path' => 'admin/config/media/browser',
  'parent_identifier' => 'a0ac7769dd155924a164eb528a16bc61c42033cf',
);

$dependencies = array(
  'menu_link.a0ac7769dd155924a164eb528a16bc61c42033cf' => 'menu_link.a0ac7769dd155924a164eb528a16bc61c42033cf',
);

$optional = array();

$modules = array();
