<?php
/**
 * @file
 * menu_link.cd4030d4740589db73fb7d0500725ec65c56e03c.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'user/logout',
  'link_title' => 'Logout',
  'menu_name' => 'menu-footer-links',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
  ),
  'router_path' => 'user/logout',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_footer_links' => 'menu.menu_footer_links',
);

$optional = array();

$modules = array();
