<?php
/**
 * @file
 * menu_link.df073aa5f6cf8b948d5406c708184695341dbe45.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/search/page-title',
  'link_title' => 'Page titles',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure the page titles for your site (the title in the &lt;head&gt; tag).',
    ),
  ),
  'router_path' => 'admin/config/search/page-title',
  'parent_identifier' => 'ef0082661602f85e5c700d4bd929cfa3db5d543f',
);

$dependencies = array(
  'menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f' => 'menu_link.ef0082661602f85e5c700d4bd929cfa3db5d543f',
);

$optional = array();

$modules = array();
