<?php
/**
 * @file
 * menu_link.506ba0fb5d767ad96972703db26660fce35c59a5.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/administration/admin_menu',
  'link_title' => 'Administration menu',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Adjust administration menu settings.',
    ),
  ),
  'router_path' => 'admin/config/administration/admin_menu',
  'parent_identifier' => 'ada990f9339b55d703abdf1d3baae0268477fa51',
);

$dependencies = array(
  'menu_link.ada990f9339b55d703abdf1d3baae0268477fa51' => 'menu_link.ada990f9339b55d703abdf1d3baae0268477fa51',
);

$optional = array();

$modules = array();
