<?php
/**
 * @file
 * menu_link.941a81ba0a33cd4e110ea7f1d1e1a25401dd303c.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/add/panel',
  'link_title' => 'Panel',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'A panel layout broken up into rows and columns.',
    ),
  ),
  'router_path' => 'node/add/panel',
  'parent_identifier' => '7fa6a77950f9dfec910f197544505e3fb2f92723',
);

$dependencies = array(
  'menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723' => 'menu_link.7fa6a77950f9dfec910f197544505e3fb2f92723',
);

$optional = array();

$modules = array();
