<?php
/**
 * @file
 * menu_link.5f13aea8db264c2b9d02b03b56ec9a05cb2cbc0e.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/system/googleanalytics',
  'link_title' => 'Google Analytics',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure tracking behavior to get insights into your website traffic and marketing effectiveness.',
    ),
  ),
  'router_path' => 'admin/config/system/googleanalytics',
  'parent_identifier' => '4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$dependencies = array(
  'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6' => 'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$optional = array();

$modules = array();
