<?php
/**
 * @file
 * menu_link.a818a4399a6e59779a08eb3cb05571e85148d836.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'productos',
  'link_title' => 'Productos',
  'menu_name' => 'main-menu',
  'weight' => '-47',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'productos',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.main_menu' => 'menu.main_menu',
);

$optional = array();

$modules = array();
