<?php
/**
 * @file
 * menu_link.a9dbd162a31d81a3358ce7b4850854c0fa411659.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'ofertas',
  'link_title' => 'Ofertas',
  'menu_name' => 'main-menu',
  'weight' => '-46',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'ofertas',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.main_menu' => 'menu.main_menu',
);

$optional = array();

$modules = array();
