<?php
/**
 * @file
 * menu_link.38100d856523138446277c54543e7c2faaab4ae3.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/structure/file-types',
  'link_title' => 'File types',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Manage settings for the type of files used on your site.',
    ),
  ),
  'router_path' => 'admin/structure/file-types',
  'parent_identifier' => '9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$dependencies = array(
  'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e' => 'menu_link.9866f27a9b57b4c9309f2a33b11f318c4b6c852e',
);

$optional = array();

$modules = array();
