<?php
/**
 * @file
 * variable.javascript_parsed.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'javascript_parsed',
  'content' => array(
    0 => 'misc/drupal.js',
    1 => 'profiles/pim_pam/modules/contrib/jquery_update/replace/jquery/1.7/jquery.min.js',
    2 => 'misc/jquery.once.js',
    3 => 'profiles/pim_pam/themes/adminimal_theme/js/jRespond.js',
    4 => 'profiles/pim_pam/themes/adminimal_theme/js/adminimal_theme.js',
    5 => 'profiles/pim_pam/modules/contrib/devel/devel_krumo_path.js',
    6 => 'profiles/pim_pam/modules/contrib/adminimal_admin_menu/js/jquery.min.js',
    7 => 'profiles/pim_pam/modules/contrib/adminimal_admin_menu/js/slicknav/jquery-no-conflict.slicknav.js',
    8 => 'profiles/pim_pam/modules/contrib/adminimal_admin_menu/js/adminimal_admin_menu.js',
    9 => 'profiles/pim_pam/modules/contrib/picture/picturefill2/picturefill.min.js',
    10 => 'profiles/pim_pam/modules/contrib/picture/picture.min.js',
    11 => 'profiles/pim_pam/modules/contrib/ctools/js/dropbutton.js',
    12 => 'misc/jquery.cookie.js',
    13 => 'profiles/pim_pam/modules/contrib/module_filter/js/module_filter.js',
    14 => 'misc/jquery.ba-bbq.js',
    15 => 'profiles/pim_pam/modules/contrib/module_filter/js/modules.js',
    16 => 'profiles/pim_pam/modules/contrib/module_filter/js/module_filter_tab.js',
    17 => 'profiles/pim_pam/modules/contrib/module_filter/js/dynamic_position.js',
    18 => 'misc/tableheader.js',
    19 => 'profiles/pim_pam/themes/adminimal_theme/skins/default/default.js',
    20 => 'profiles/pim_pam/modules/contrib/admin_menu/admin_menu.js',
    'refresh:es' => 'waiting',
    'refresh:ca' => 'waiting',
    'refresh:de' => 'waiting',
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
