<?php
/**
 * @file
 * variable.entity_translation_settings_taxonomy_term__product_categories.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'entity_translation_settings_taxonomy_term__product_categories',
  'content' => array(
    'default_language' => 'es',
    'hide_language_selector' => 1,
    'exclude_language_none' => 1,
    'lock_language' => 1,
    'shared_fields_original_only' => 0,
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
