<?php
/**
 * @file
 * variable.locale_language_providers_weight_language.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'locale_language_providers_weight_language',
  'content' => array(
    'locale-user' => '-10',
    'locale-url' => '-9',
    'locale-session' => '-8',
    'locale-browser' => '-7',
    'language-default' => '-6',
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
