<?php
/**
 * @file
 * variable.language_default.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'language_default',
  'content' => (object) array(
    'language' => 'es',
    'name' => 'Spanish',
    'native' => 'Español',
    'direction' => '0',
    'enabled' => '1',
    'plurals' => '2',
    'formula' => '($n!=1)',
    'domain' => '',
    'prefix' => 'es',
    'weight' => '-10',
    'javascript' => 'PjJX0KYzehuAjb3oTzOC2vQkwSqi76mVUnpiDouRHUo',
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
